### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by kw-andy** [AVOCarbon/tableau-reporting#5]
What is the difference between QA-002_CustomerComplaint.sql and Qa-002_CustomerComplaint2.sql?

Dans Qa-002_CustomerComplaint2.sql, qu'est ce que la sous requête complaint ?

**Comment by TheBadgerNovice** [comment]
What is the difference between QA-002_CustomerComplaint.sql and Qa-002_CustomerComplaint2.sql?

Dans un Dashboard, parfois il est nécessaire d'utiliser plusieurs requêtes sql (source de donnée Tableau).
Selon les dashboards j'ai utiliser entre 1 et 3 sources de données.
Je numérote alors à la fin de chaque nom le numéro de la source de donnée en question.

Dans Qa-002_CustomerComplaint2.sql, qu'est ce que la sous requête complaint ?
complaint est le nom que j'ai donnée à une requête.
Afin d'optimiser les temps d’exécution, en amont de la jointure je crée des sous requêtes que je nomme afin de réduire le nombre de lignes.
Exemple : 
With complaint AS ( select .. from .. where .. )
